### PR TITLE
Add tests for Scala 3 macros

### PR DESCRIPTION
**Pull request by Flowdalic**
This adds a few simple and short tests for the Scala 3 macros. Especially for the central deconstructMessageFormat() macro, which was previously broken and fixed with 66ac4a718112 ("Fixed Scala 3 macros (#26)").

### CODE REVIEW

**Comment by Flowdalic** [comment]
@vy In [#26](https://github.com/apache/logging-log4j-scala/pull/26#issuecomment-1719004954) @pjfanning asked for tests for the macros. Here are the tests that I used to debug and fix the macros. Nothing fancy, but I figured I try to contribute before those tests are lost.

**Comment by vy** [comment]
@Flowdalic, thanks so much! Would you mind fixing the compilation errors, please?

**Comment by Flowdalic** [comment]
> @Flowdalic, thanks so much! Would you mind fixing the compilation errors, please?

Sure. Couldn't figure out that I need `./mvnw test  -pl log4j-api-scala_3` to run just the Scala 3 tests. Should compile now :)

**Comment by vy** [comment]
@Flowdalic, I also need your commits to be signed to be able to merge this PR.

I appreciate it if you can sign the commits. This will give you the full credit in the `git log`. Otherwise, I can apply your changes myself, I will appear as the committer – though I will link to this issue, where those who are curious can trace back to you.

**Comment by Flowdalic** [comment]
> I appreciate it if you can sign the commits.

Done.

**Comment by vy** [comment]
@Flowdalic, I think you did a `git commit -s`. You should rather have done `git commit -S`. Could you try that and `-f push` again?

**Comment by Flowdalic** [comment]
> @Flowdalic, I think you did a `git commit -s`. You should rather have done `git commit -S`. Could you try that and `-f push` again?

Oh, you really asked for an OpenPGP signed commit. Not just a signed off trailer. Done.
